### ISSUE TITLE
Hey M8 how do u create like login system like ur site?

### ISSUE THREAD

**Issue by Pollogy** [ArixProject/MultiOgar-Edited-Unlimited#2]
Theanks! xD

**Comment by hossem123** [comment]
its really suck try my own level system and its with facebook login [](http://agar.tn/)

**Comment by zettabyte918** [comment]
its really suck try my own level system http://agar.tn/ its with facebook login

**Comment by ArixProject** [comment]
@Mr-BrockLee like agarix?

**Comment by ArixProject** [comment]
Try the command `/account`
