### ISSUE TITLE
Missing the PluginHandler....

### ISSUE THREAD

**Issue by a632283395** [ArixProject/MultiOgar-Edited-Unlimited#4]
When I start the server, the console noticed me that 
Error：Cannot find module './PluginHandler'
I try to find if there is any mistake I got, but nothing founded.

And the PluginHandler seems to be required by the GameServer.js.
So.... Where is the PluginHandler.js?
Is that a BUG?

**Comment by ArixProject** [comment]
Probably there was a bug when I added server files
Right now I'll add

**Comment by a632283395** [comment]
Thanks for fast reply！Btw, do u have the client code？I want to build on my own server for research.

**Comment by ArixProject** [comment]
Fixed it! Customer code is

**Comment by ArixProject** [comment]
I repaired it! I have a client code

**Comment by a632283395** [comment]
Thanks for fast fixing. I mean the Agar.io's client code. Now I need to open agar.io in order to play my private server,.but I need to play my private server without open the agar.io, I want build a game client on my own server rather than the server.

**Comment by a632283395** [comment]
Could u please send me a copy？

**Comment by ArixProject** [comment]
Try to go to the site agarahg.tk
And go to your server (there's a server server in the servers, well, yours)
And there it is written ip, if it to converge with your server that you can come
If not then change

**Comment by a632283395** [comment]
It works! Successfuly connected and played on my server. Can I have the source?

**Comment by ArixProject** [comment]
Yes! You can get the source
[https://github.com/CigarProject/Cigar](Cigar)

**Comment by AlexHGaming** [comment]
@ArixProject 
>Try to go to the site agarahg.tk

ooooooooooooo

**Comment by ChamForever** [comment]
@AlexHGaming yooooo
